package com.automl.automl;

public enum MLModelType {

    DECISION_TREE_CLASSIFIER,
    RANDOM_FOREST_CLASSIFIER,
    K_NEAREST_NEIGHBORS,
    SCV,
    NAIVE_BAYES,
    DECISION_TREE_REGRESSOR,
    RANDOM_FOREST_REGRESSOR,
    LINEAR_REGRESSION,
    SVR,
    ELASTIC_NET_CV
}
